#include <Arduino.h>
#include <lvgl.h>
#include "lvgl_port.h"
#include "wifi_gui.h"
#include "ui/ui.h"  // generated by EEZ Studio

void setup() {
  Serial.begin(115200);

  lv_init();
  lv_tick_set_cb([]() -> uint32_t { return millis(); });
  if (!lvgl_display_init()) Serial.println("Display init failed");
  if (!lvgl_touch_init()) Serial.println("Touch init failed");

  ui_init();
  wifi_gui_init();
}

void loop() {
  lv_timer_handler();
  ui_tick();  // runs EEZ flow and screen updates
  wifi_gui_loop();
  delay(5);
}
