// Startup and main loop. Layers:
//   drivers/   hardware (display, touch, codec, backlight, LED) and the LVGL port
//   managers/  features with begin()/loop() (storage, battery, audio, mic, WiFi, OTA)
//   gui/       EEZ Studio glue: native actions and variables for each screen
//   ui/        generated by EEZ Studio (never edit)
#include <Arduino.h>
#include <Wire.h>
#include <lvgl.h>
#include "drivers/lvgl_port.h"
#include "managers/storage_manager.h"
#include "managers/battery_manager.h"
#include "managers/audio_manager.h"
#include "managers/mic_manager.h"
#include "managers/wifi_manager.h"
#include "managers/ota_manager.h"
#include "gui/main_screen.h"
#include "gui/wifi_screens.h"
#include "ui/ui.h"
#include "app_config.h"

void setup() {
  Serial.begin(115200);
  Wire.begin(I2C_PIN_SDA, I2C_PIN_SCL, I2C_BUS_HZ);  // shared bus: touch, audio codec, header P4

  lv_init();
  lv_tick_set_cb([]() -> uint32_t { return millis(); });
  if (!lvgl_display_init()) Serial.println("Display init failed");
  if (!lvgl_touch_init()) Serial.println("Touch init failed");
  ui_init();

  storage_manager.begin();  // SD card, mounted in the background
  battery_manager.begin();
  audio_manager.begin();    // after storage (unmount hook)
  mic_manager.begin();      // after audio: the mic is clocked by playback's I2S0
  wifi_manager.begin();
  ota_manager.begin();

  main_screen_init();
  wifi_screens_init();
}

void loop() {
  lv_timer_handler();
  ui_tick();  // runs EEZ flow and screen updates

  wifi_manager.loop();
  ota_manager.loop();
  audio_manager.loop();
  battery_manager.loop();

  main_screen_loop();
  wifi_screens_loop();
  delay(5);
}
