#include <Arduino.h>
#include <lvgl.h>
#include "lvgl_display.h"
#include "ui/ui.h"  // generated by EEZ Studio

void setup() {
  Serial.begin(115200);

  lv_init();
  lv_tick_set_cb([]() -> uint32_t { return millis(); });
  if (!lvgl_display_init()) Serial.println("Display init failed");

  ui_init();
}

void loop() {
  lv_timer_handler();
  ui_tick();  // runs EEZ flow and screen updates
  delay(5);
}
